version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
  # db:
  #     image: mysql:5.7.22
  #     environment:
  #         MYSQL_DATABASE: admin
  #         MYSQL_USER: root
  #         MYSQL_PASSWORD: root
  #         MYSQL_ROOT_PASSWORD: root
  #     volumes:
  #         - ./storage/dbdata:/var/lib/mysql
  #     ports:
  #         - 33066:3306
